version: '3.8'

services:
  app:
    image: your-image-name
    build:
      context: .
      target: runner
    ports:
      - "80:80"
    environment:
      - PORT=80
      - HOSTNAME=0.0.0.0
    expose:
      - "80"
    command: ["node", "server.js"]