import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-auto flex min-h-screen w-4/5 flex-col justify-between p-4">
          <Navbar />
          <main className="w-full text-center text-8xl font-bold tracking-wide">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
